# 服务端口的配置
server:
  port: 8990
  context: /
# 数据库配置
database:
  mysql:
    host: 127.0.0.1
    port: 3306
    dbname: jy-admin-db
    username: root
    password: 123456
    config: charset=utf8&parseTime=True&loc=Local
# nosql数据的配置
nosql:
  redis:
    host: 127.0.0.1:6379
    password:
    db: 0
  es:
    host: 127.0.0.1
    port: 9300
    password: 456